### PR TITLE
Support in-cluster configuration

### LINKED ISSUE #54: Support in-cluster auth
Hi,

it would be nice if node-shell would work with in-cluster auth (without having a kubeconfig file)

### PR DESCRIPTION
**Pull request by jkroepke**
Fix #54

### CODE REVIEW

**Comment by jkroepke** [comment]
@kvaps could you take a look here?

**Comment by jkroepke** [comment]
@kvaps could you please take a look here?

**Comment by jkroepke** [comment]
Done!

**Comment by jkroepke** [comment]
@kvaps I would like to give a welcome reminder here. I adjusted the version as requested.

**Comment by kvaps** [comment]
Merged in `v1.8.1` thanks!

**Pull request merged**
