### PR TITLE
Adds support for passing through context and kubeconfig flags

### PR DESCRIPTION
**Pull request by deiga**
This allows people with multiple clusters to use this tool more easily

### CODE REVIEW

**Comment by kvaps** [comment]
Hi @deiga,
Thanks for your PR, however the arrays will not going to work with the classic bourne shell (`/bin/sh` ).
We should consider the need to increase the shell dependency to `/bin/bash` or better stick to `/bin/sh`.

Anyway I'm thinking it might be better to passthrough all the dash options directly to `kubectl`, because there is much more of them, eg user might want to use `--cluster` and `--server` as well.

**Comment by deiga** [comment]
@kvaps That is a good point, I didn't take POSIX compliance into account. I can fiddle with something or we can just change it to pass all given params except for the ones node-shell uses

**Comment by deiga** [comment]
@kvaps I fixed the POSIX compliance issue but got stuck on how to implement passing all dash options to `kubectl`. Without arrays, I couldn't think of a safe way to do this, other than eval

**Comment by kvaps** [comment]
@deiga awesome work, thanks!

**Pull request merged**
